version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - server.port=9090

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-stats-db
    environment:
      - POSTGRES_PASSWORD=iamroot
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm-stats

  ewm-service:
    build: ewm-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - SERVICES_STATSSERVICE_URI=http://stats-server:9090
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-main-db
    environment:
      - POSTGRES_PASSWORD=iamroot
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm